import type { MetadataRoute } from 'next'
import { siteConfig } from '@/lib/seo/site-config'

const baseUrl = siteConfig.url

const staticRoutes = [
  { path: '', priority: 1.0, changeFreq: 'weekly' as const },
  { path: '/features', priority: 0.9, changeFreq: 'weekly' as const },
  { path: '/pricing', priority: 0.9, changeFreq: 'weekly' as const },
  { path: '/docs', priority: 0.8, changeFreq: 'weekly' as const },
  { path: '/docs/getting-started', priority: 0.7, changeFreq: 'weekly' as const },
  { path: '/docs/getting-started/quickstart', priority: 0.7, changeFreq: 'weekly' as const },
  { path: '/docs/getting-started/installation', priority: 0.7, changeFreq: 'weekly' as const },
  { path: '/docs/getting-started/authentication', priority: 0.7, changeFreq: 'weekly' as const },
  { path: '/docs/getting-started/first-app', priority: 0.7, changeFreq: 'weekly' as const },
  { path: '/docs/license-keys', priority: 0.7, changeFreq: 'weekly' as const },
  { path: '/docs/license-keys/types', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/license-keys/creating', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/license-keys/validation', priority: 0.7, changeFreq: 'weekly' as const },
  { path: '/docs/license-keys/best-practices', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/security', priority: 0.7, changeFreq: 'weekly' as const },
  { path: '/docs/security/hwid', priority: 0.7, changeFreq: 'weekly' as const },
  { path: '/docs/security/encryption', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/security/anti-tamper', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/security/threat-monitoring', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/sdk', priority: 0.7, changeFreq: 'weekly' as const },
  { path: '/docs/sdk/csharp', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/sdk/cpp', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/sdk/python', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/sdk/javascript', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/sdk/device-activation', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/dashboard', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/dashboard/analytics', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/dashboard/audit-logs', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/dashboard/blacklist', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/dashboard/team', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/dashboard/variables', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/account', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/account/two-factor', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/account/api-keys', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/account/notifications', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/account/ip-whitelist', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/account/backups', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/account/environments', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/account/health', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/advanced', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/advanced/bots', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/advanced/chat-rooms', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/advanced/webhooks', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/advanced/custom-domains', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/advanced/scheduled-actions', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/advanced/organizations', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/advanced/seller-api', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/advanced/custom-responses', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/advanced/ai-assistant', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/api-reference', priority: 0.7, changeFreq: 'weekly' as const },
  { path: '/docs/api-reference/auth', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/api-reference/license-keys', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/api-reference/users', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/api-reference/webhooks', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/faq', priority: 0.6, changeFreq: 'weekly' as const },
  { path: '/docs/faq/general', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/faq/billing', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/docs/faq/troubleshooting', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/api-docs', priority: 0.8, changeFreq: 'weekly' as const },
  { path: '/sdks', priority: 0.8, changeFreq: 'weekly' as const },
  { path: '/blog', priority: 0.7, changeFreq: 'daily' as const },
  { path: '/faq', priority: 0.8, changeFreq: 'weekly' as const },
  { path: '/contact', priority: 0.6, changeFreq: 'monthly' as const },
  { path: '/about', priority: 0.6, changeFreq: 'monthly' as const },
  { path: '/terms', priority: 0.4, changeFreq: 'monthly' as const },
  { path: '/privacy', priority: 0.4, changeFreq: 'monthly' as const },
  { path: '/cookies', priority: 0.3, changeFreq: 'monthly' as const },
  { path: '/status', priority: 0.5, changeFreq: 'daily' as const },
  { path: '/changelog', priority: 0.5, changeFreq: 'weekly' as const },
  { path: '/support', priority: 0.6, changeFreq: 'monthly' as const },
  { path: '/integrations', priority: 0.7, changeFreq: 'weekly' as const },
  { path: '/downloads', priority: 0.6, changeFreq: 'monthly' as const },
]

const seoLandingRoutes = [
  { path: '/software-authentication', priority: 0.7 },
  { path: '/license-key-authentication', priority: 0.7 },
  { path: '/license-management', priority: 0.7 },
  { path: '/desktop-authentication', priority: 0.7 },
  { path: '/authentication-api', priority: 0.7 },
  { path: '/developer-authentication', priority: 0.7 },
  { path: '/hwid-authentication', priority: 0.8 },
  { path: '/hwid-lock', priority: 0.8 },
  { path: '/software-protection', priority: 0.7 },
  { path: '/license-server', priority: 0.7 },
  { path: '/authentication-sdk', priority: 0.7 },
  { path: '/csharp-authentication', priority: 0.6 },
  { path: '/cpp-authentication', priority: 0.6 },
  { path: '/discord-authentication', priority: 0.6 },
  { path: '/telegram-authentication', priority: 0.6 },
  { path: '/secure-login-system', priority: 0.7 },
  { path: '/game-authentication', priority: 0.6 },
  { path: '/launcher-authentication', priority: 0.6 },
  { path: '/api-security', priority: 0.7 },
  { path: '/jwt-authentication', priority: 0.6 },
  { path: '/rest-authentication', priority: 0.6 },
  { path: '/license-validation', priority: 0.7 },
  { path: '/application-security', priority: 0.7 },
  { path: '/cloud-authentication', priority: 0.7 },
]

export default function sitemap(): MetadataRoute.Sitemap {
  const staticEntries = staticRoutes.map((route) => ({
    url: `${baseUrl}${route.path}`,
    lastModified: new Date(),
    changeFrequency: route.changeFreq,
    priority: route.priority,
  }))

  const landingEntries = seoLandingRoutes.map((route) => ({
    url: `${baseUrl}${route.path}`,
    lastModified: new Date(),
    changeFrequency: 'monthly' as const,
    priority: route.priority,
  }))

  return [...staticEntries, ...landingEntries]
}
