export const landingPages = {
  'software-authentication': {
    title: 'Software Authentication | Protect Your Applications',
    description: 'Enterprise-grade software authentication platform. Protect your desktop and web applications with HWID locking, license keys, and AI-powered threat detection.',
    h1: 'Enterprise Software Authentication Platform',
    intro: 'Protect your software from piracy and unauthorized access with RinoxAuth\'s comprehensive authentication platform.',
    features: [
      'HWID-based device locking',
      'License key generation and validation',
      'AI-powered threat detection',
      'Real-time session monitoring',
      'Developer SDK for all platforms',
    ],
  },
  'license-key-authentication': {
    title: 'License Key Authentication System | Key Management',
    description: 'Secure license key authentication and management system. Generate, validate, and manage software license keys with ease.',
    h1: 'License Key Authentication & Management',
    intro: 'Full-featured license key system with support for time-based, lifetime, and usage-based licenses.',
    features: [
      'Automatic license key generation',
      'Time-based and lifetime licenses',
      'Usage-based key tracking',
      'Bulk key generation',
      'License validation API',
    ],
  },
  'license-management': {
    title: 'License Management Platform | Software Licensing',
    description: 'Complete license management platform for software vendors. Track, manage, and validate software licenses in real-time.',
    h1: 'Software License Management Platform',
    intro: 'Manage all your software licenses from a single dashboard with real-time analytics and reporting.',
    features: [
      'Centralized license dashboard',
      'Real-time license tracking',
      'Automated license expiration',
      'License revocation and suspension',
      'Detailed analytics and reports',
    ],
  },
  'desktop-authentication': {
    title: 'Desktop Authentication | Secure Desktop Apps',
    description: 'Secure desktop application authentication with HWID locking, offline mode, and cross-platform SDK support.',
    h1: 'Desktop Application Authentication',
    intro: 'Protect your desktop applications with hardware-bound authentication that works on Windows, macOS, and Linux.',
    features: [
      'Windows, macOS, Linux support',
      'Hardware ID (HWID) binding',
      'Offline authentication mode',
      'C++ and C# native SDKs',
      'Automatic updates integration',
    ],
  },
  'authentication-api': {
    title: 'Authentication API | REST API for Developers',
    description: 'Powerful REST API for user authentication, license validation, and session management. Easy integration with any programming language.',
    h1: 'Authentication API for Developers',
    intro: 'Simple, powerful REST API that handles authentication, license validation, and session management.',
    features: [
      'RESTful API design',
      'JWT-based authentication',
      'Session management',
      'Rate limiting',
      'Webhook integration',
    ],
  },
  'developer-authentication': {
    title: 'Developer Authentication Tools | SDK & API',
    description: 'Complete developer authentication toolkit with SDKs for Python, C#, C++, JavaScript, and more.',
    h1: 'Developer Authentication Toolkit',
    intro: 'Everything developers need to implement secure authentication in their applications.',
    features: [
      'SDKs for all major languages',
      'Comprehensive documentation',
      'Quick-start examples',
      'API playground',
      'Community support',
    ],
  },
  'hwid-authentication': {
    title: 'HWID Authentication | Hardware-Based Security',
    description: 'Hardware-based authentication using unique device identifiers. Prevent unauthorized access with HWID locking.',
    h1: 'HWID Authentication System',
    intro: 'Bind licenses to specific hardware using unique device identifiers for maximum security.',
    features: [
      'Hardware fingerprinting',
      'Multi-component HWID',
      'HWID reset management',
      'Device group management',
      'Anti-spoofing protection',
    ],
  },
  'hwid-lock': {
    title: 'HWID Lock | Device-Based License Binding',
    description: 'Lock software licenses to specific hardware with HWID binding. Prevent license sharing and piracy.',
    h1: 'Hardware ID (HWID) Locking',
    intro: 'Bind your software licenses to specific hardware configurations to prevent unauthorized sharing.',
    features: [
      'Hardware-bound licensing',
      'Tamper-resistant HWID',
      'Controlled HWID resets',
      'Device management dashboard',
      'Cross-platform HWID',
    ],
  },
  'software-protection': {
    title: 'Software Protection | Anti-Piracy Solutions',
    description: 'Comprehensive software protection platform with anti-piracy features, code obfuscation, and integrity checking.',
    h1: 'Software Protection & Anti-Piracy',
    intro: 'Multi-layered software protection to prevent cracking, reverse engineering, and unauthorized distribution.',
    features: [
      'Anti-debugging protection',
      'Code integrity verification',
      'Memory protection',
      'Network-based validation',
      'Automated ban system',
    ],
  },
  'license-server': {
    title: 'License Server | Cloud License Management',
    description: 'Cloud-based license server for software vendors. Real-time license validation and management.',
    h1: 'Cloud License Server',
    intro: 'Host your license management in the cloud with real-time validation and instant scalability.',
    features: [
      'Cloud-hosted infrastructure',
      'Real-time license validation',
      'Automatic scaling',
      '99.9% uptime SLA',
      'Global CDN distribution',
    ],
  },
  'authentication-sdk': {
    title: 'Authentication SDK | Developer Integration Kits',
    description: 'Software development kits for integrating authentication into your applications. Supports C#, C++, Python, and more.',
    h1: 'Authentication SDK for Developers',
    intro: 'Ready-to-use SDKs that make implementing authentication in your application simple and fast.',
    features: [
      'Native C++ SDK',
      'C# .NET SDK',
      'Python SDK',
      'JavaScript/TypeScript SDK',
      'Java SDK',
      'Rust SDK',
    ],
  },
}
