export const siteConfig = {
  name: 'RinoxAuth',
  tagline: 'Enterprise Authentication & License Management Platform',
  description: 'Enterprise-grade authentication, license management, and software protection platform. HWID lock, AI-powered threat detection, license keys, and developer SDK.',
  url: 'https://authsys.dpdns.org',
  ogImage: '/logo.png',
  author: 'RinoxAuth Team',
  twitterHandle: '@RinoxAuth',
  links: {
    github: 'https://github.com/RinoxAuth/RinoxAuth',
    discord: 'https://discord.gg/rinoxauth',
    telegram: 'https://t.me/rinoxauth',
  },
  contact: {
    email: 'support@authsys.com',
    address: 'San Francisco, CA',
  },
  navItems: [
    { label: 'Home', href: '/' },
    { label: 'Features', href: '/features' },
    { label: 'Pricing', href: '/pricing' },
    { label: 'Documentation', href: '/docs' },
    { label: 'API', href: '/api-docs' },
    { label: 'SDK', href: '/sdks' },
    { label: 'Blog', href: '/blog' },
    { label: 'FAQ', href: '/faq' },
    { label: 'Contact', href: '/contact' },
  ],
  footerItems: {
    product: [
      { label: 'Features', href: '/features' },
      { label: 'Pricing', href: '/pricing' },
      { label: 'API', href: '/api-docs' },
      { label: 'SDK', href: '/sdks' },
      { label: 'Integrations', href: '/integrations' },
      { label: 'Changelog', href: '/changelog' },
    ],
    developers: [
      { label: 'Documentation', href: '/docs' },
      { label: 'API Reference', href: '/api-docs' },
      { label: 'C# SDK', href: '/sdks/csharp' },
      { label: 'C++ SDK', href: '/sdks/cpp' },
      { label: 'Python SDK', href: '/sdks/python' },
      { label: 'Status', href: '/status' },
    ],
    resources: [
      { label: 'Blog', href: '/blog' },
      { label: 'FAQ', href: '/faq' },
      { label: 'Support', href: '/contact' },
      { label: 'Terms', href: '/terms' },
      { label: 'Privacy', href: '/privacy' },
      { label: 'About', href: '/about' },
    ],
  },
}
