"""add_hwid_enabled_and_timezone_aware_datetimes

Revision ID: b0bef6c6c78c
Revises: 7e81331dd362
Create Date: 2026-05-14 00:25:47.711295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b0bef6c6c78c'
down_revision: Union[str, None] = '7e81331dd362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'timestamp',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('admin_users', 'created_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('admin_users', 'last_login',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('ai_agent_logs', 'timestamp',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('applications', sa.Column('owner_id', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('hwid_enabled', sa.Boolean(), nullable=True))
    op.alter_column('applications', 'created_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('applications', 'updated_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_applications_owner_id'), 'applications', ['owner_id'], unique=True)
    op.alter_column('blacklist', 'expires_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('blacklist', 'created_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('developer_accounts', 'created_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('end_users', 'subscription_expires_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('end_users', 'ban_expires_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('end_users', 'last_login_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('end_users', 'created_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('license_keys', 'created_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('license_keys', 'expires_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('sessions', 'expires_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('sessions', 'created_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('variables', 'created_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('webhooks_log', 'delivered_at',
                existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhooks_log', 'delivered_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('variables', 'created_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('sessions', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('license_keys', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('license_keys', 'created_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('end_users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('end_users', 'last_login_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('end_users', 'ban_expires_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('end_users', 'subscription_expires_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('developer_accounts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('blacklist', 'created_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('blacklist', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_applications_owner_id'), table_name='applications')
    op.alter_column('applications', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('applications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_column('applications', 'hwid_enabled')
    op.drop_column('applications', 'owner_id')
    op.alter_column('ai_agent_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('admin_users', 'last_login',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('admin_users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('activity_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
                type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###
